FROM node:18-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install --production

# Copy consumer code
COPY consumer ./consumer

# Start consumer
CMD ["node", "consumer/index.js"]
